### ISSUE TITLE
Slack message when group or profile image is changed

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#151]
# Problem
- We need to make sure there's no inappropriate content on the hub in terms of the kinds of pictures users and groups will upload as their display picture

# Solution
- make a `#image_uploads` channel on slack
- whenever an image is uploaded to the the hub, simply post a link to slack
- get a couple of people to join the channel who can passively make sure everything being upload is a-ok

**Comment by Richenda** [comment]
Wow this is so cool!

**Comment by Manoj-nathwani** [comment]
@taymonbeal - image uploads are broken locally so can you sort this out please. I've got the code done, it just needs to be implemented and tested

# Code to add
- in the `Profile/views.py` file, under `if request.method == 'POST':` for `edit_profile` add:
```
if 'image' in form.changed_data:
    url = os.environ['SLACK_WEBHOOK_URL_FOR_IMAGE_UPLOADS']
    post_data = {"text": "<IMAGE_URL>"}
    response = requests.post(
        url, data=json.dumps(post_data),
        headers={'Content-Type': 'application/json'}
    )
```
- I've already added the `SLACK_WEBHOOK_URL_FOR_IMAGE_UPLOADS` env to prod and lastpass

**Comment by taymonbeal** [comment]
What do you mean "image uploads are broken locally"?

**Comment by Manoj-nathwani** [comment]
Try it, I was getting a redis error

**Comment by Manoj-nathwani** [comment]
```
[2019-02-13 07:34:23 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-02-13 07:34:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-02-13 07:34:23 +0000] [1] [INFO] Using worker: sync
[2019-02-13 07:34:23 +0000] [8] [INFO] Booting worker with pid: 8
Client-Request-ID=7a62fe98-2f62-11e9-9435-0242ac130006 Retry policy did not allow for a retry: Server-Timestamp=Wed, 13 Feb 2019 07:39:21 GMT, HTTP status code=404, Exception=Not Found.
Client-Request-ID=7a6e7cdc-2f62-11e9-839e-0242ac130006 Retry policy did not allow for a retry: Server-Timestamp=Wed, 13 Feb 2019 07:39:21 GMT, HTTP status code=404, Exception=Not Found<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.</Message></Error>.
Internal Server Error: /profile/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/profiles/views.py", line 73, in edit_profile
    profile.save()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 809, in _save_table
    for f in non_pks]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 809, in <listcomp>
    for f in non_pks]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.6/site-packages/storages/backends/azure_storage.py", line 250, in _save
    timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 614, in create_blob_from_stream
    initialization_vector=iv
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 99, in _upload_blob_chunks
    range_ids = [f.result() for f in futures]
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 99, in <listcomp>
    range_ids = [f.result() for f in futures]
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 211, in process_chunk
    return self._upload_chunk_with_progress(chunk_offset, chunk_bytes)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 225, in _upload_chunk_with_progress
    range_id = self._upload_chunk(chunk_offset, chunk_data)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 270, in _upload_chunk
    timeout=self.timeout,
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 1143, in _put_block
    self._perform_request(request)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureMissingResourceHttpError: Not Found
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.</Message></Error>
```

**Comment by Manoj-nathwani** [comment]
@taymonbeal 
```
[2019-02-13 07:34:23 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-02-13 07:34:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-02-13 07:34:23 +0000] [1] [INFO] Using worker: sync
[2019-02-13 07:34:23 +0000] [8] [INFO] Booting worker with pid: 8
Client-Request-ID=7a62fe98-2f62-11e9-9435-0242ac130006 Retry policy did not allow for a retry: Server-Timestamp=Wed, 13 Feb 2019 07:39:21 GMT, HTTP status code=404, Exception=Not Found.
Client-Request-ID=7a6e7cdc-2f62-11e9-839e-0242ac130006 Retry policy did not allow for a retry: Server-Timestamp=Wed, 13 Feb 2019 07:39:21 GMT, HTTP status code=404, Exception=Not Found<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.</Message></Error>.
Internal Server Error: /profile/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/profiles/views.py", line 73, in edit_profile
    profile.save()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 809, in _save_table
    for f in non_pks]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 809, in <listcomp>
    for f in non_pks]
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 288, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 49, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.6/site-packages/storages/backends/azure_storage.py", line 250, in _save
    timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 614, in create_blob_from_stream
    initialization_vector=iv
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 99, in _upload_blob_chunks
    range_ids = [f.result() for f in futures]
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 99, in <listcomp>
    range_ids = [f.result() for f in futures]
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 211, in process_chunk
    return self._upload_chunk_with_progress(chunk_offset, chunk_bytes)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 225, in _upload_chunk_with_progress
    range_id = self._upload_chunk(chunk_offset, chunk_data)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_upload_chunking.py", line 270, in _upload_chunk
    timeout=self.timeout,
  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/blockblobservice.py", line 1143, in _put_block
    self._perform_request(request)
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureMissingResourceHttpError: Not Found
<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.</Message></Error>
```

**Comment by Manoj-nathwani** [comment]
@taymonbeal ⬆️

**Comment by michaltrzesimiech** [comment]
CC @taymonbeal

**Comment by taymonbeal** [comment]
Is this urgent enough that it's worth doing a quick patch like this, or can it wait until we have more general tools in place for workflow management?

**Comment by michaltrzesimiech** [comment]
This can definitely wait until post freeze
