### ISSUE TITLE
"ModuleNotFoundError: No module named 'azure.common'" when running "docker-compose up"

### ISSUE THREAD

**Issue by patbl** [rtcharity/eahub.org#861]
@david-mears and I get this error. He has a Mac, and I have a Mac and a Linux computer, and I get it only on the Mac.

Commenting out this line allows the command to succeed:

https://github.com/rtcharity/eahub.org/blob/e865ba778cbab10d651378a798bce6de2f3f254e/eahub/config/settings.py#L39

There's some discussion here: https://app.slack.com/client/T07S8FTJQ/CHGV507EW/thread/CHGV507EW-1572811476.001800

Here's the full output:

```
[21:32:15] ~/projects/eahub.org master ➜ docker-compose up
Starting eahuborg_objstore_1  ... done
Starting eahuborg_mail_1      ... done
Starting eahuborg_cache_1     ... done
Starting eahuborg_db_1        ... done
Starting eahuborg_webdriver_1 ... done
Starting eahuborg_chrome_1    ... done
Starting eahuborg_firefox_1   ... done
Starting eahuborg_web_1       ... done
Attaching to eahuborg_db_1, eahuborg_webdriver_1, eahuborg_cache_1, eahuborg_objstore_1, eahuborg_mail_1, eahuborg_chrome_1, eahuborg_firefox_1, eahuborg_web_1
webdriver_1  | 2019-12-27 05:32:40,756 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
db_1         | 2019-12-27 05:32:40.382 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2019-12-27 05:32:40.382 UTC [1] LOG:  listening on IPv6 address "::", port 5432
webdriver_1  | 2019-12-27 05:32:40,764 INFO supervisord started with pid 8
webdriver_1  | 2019-12-27 05:32:41,769 INFO spawned: 'selenium-hub' with pid 11
cache_1      | 1:C 27 Dec 05:32:40.099 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache_1      |                 _._
cache_1      |            _.-``__ ''-._
cache_1      |       _.-``    `.  `_.  ''-._           Redis 3.2.7 (00000000/0) 64 bit
cache_1      |   .-`` .-```.  ```\/    _.,_ ''-._
cache_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
cache_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
cache_1      |  |    `-._   `._    /     _.-'    |     PID: 1
cache_1      |   `-._    `-._  `-./  _.-'    _.-'
cache_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
cache_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io
cache_1      |   `-._    `-._`-.__.-'_.-'    _.-'
cache_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
cache_1      |  |    `-._`-._        _.-'_.-'    |
cache_1      |   `-._    `-._`-.__.-'_.-'    _.-'
cache_1      |       `-._    `-.__.-'    _.-'
cache_1      |           `-._        _.-'
cache_1      |               `-.__.-'
cache_1      |
objstore_1   | Azure Blob Storage Emulator listening on port 8002
mail_1       | Starting MailCatcher
chrome_1     | 2019-12-27 05:32:41,732 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
chrome_1     | 2019-12-27 05:32:41,736 INFO supervisord started with pid 7
cache_1      | 1:M 27 Dec 05:32:40.114 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cache_1      | 1:M 27 Dec 05:32:40.114 # Server started, Redis version 3.2.7
cache_1      | 1:M 27 Dec 05:32:40.115 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
firefox_1    | 2019-12-27 05:32:41,746 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
db_1         | 2019-12-27 05:32:40.394 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
webdriver_1  | Starting Selenium Hub with configuration:
webdriver_1  | 2019-12-27 05:32:41,799 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
db_1         | 2019-12-27 05:32:40.432 UTC [23] LOG:  database system was shut down at 2019-11-25 17:50:21 UTC
db_1         | 2019-12-27 05:32:40.493 UTC [1] LOG:  database system is ready to accept connections
firefox_1    | 2019-12-27 05:32:41,753 INFO supervisord started with pid 7
mail_1       | ==> smtp://0.0.0.0:1025
webdriver_1  | {
webdriver_1  |   "host": "0.0.0.0",
webdriver_1  |   "port": 4444,
webdriver_1  |   "role": "hub",
webdriver_1  |   "maxSession": 5,
webdriver_1  |   "newSessionWaitTimeout": -1,
webdriver_1  |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
webdriver_1  |   "throwOnCapabilityNotPresent": true,
webdriver_1  |   "jettyMaxThreads": -1,
webdriver_1  |   "cleanUpCycle": 5000,
webdriver_1  |   "browserTimeout": 0,
webdriver_1  |   "timeout": 1800,
webdriver_1  |   "debug": false
webdriver_1  | }
cache_1      | 1:M 27 Dec 05:32:40.121 * DB loaded from disk: 0.006 seconds
cache_1      | 1:M 27 Dec 05:32:40.121 * The server is now ready to accept connections on port 6379
mail_1       | ==> http://0.0.0.0:1080
chrome_1     | 2019-12-27 05:32:42,740 INFO spawned: 'xvfb' with pid 10
chrome_1     | 2019-12-27 05:32:42,744 INFO spawned: 'selenium-node' with pid 11
firefox_1    | 2019-12-27 05:32:42,756 INFO spawned: 'xvfb' with pid 10
firefox_1    | 2019-12-27 05:32:42,760 INFO spawned: 'selenium-node' with pid 11
webdriver_1  | 05:32:43.688 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1     | 2019-12-27 05:32:43,748 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
chrome_1     | 2019-12-27 05:32:43,748 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1    | 2019-12-27 05:32:43,764 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1    | 2019-12-27 05:32:43,765 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
firefox_1    | Connecting to the Hub using the host webdriver and port 4444
chrome_1     | Connecting to the Hub using the host webdriver and port 4444
webdriver_1  | 05:32:44.328 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
web_1        | [2019-12-27 05:32:44 +0000] [1] [INFO] Starting gunicorn 19.9.0
web_1        | [2019-12-27 05:32:44 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1        | [2019-12-27 05:32:44 +0000] [1] [INFO] Using worker: sync
web_1        | [2019-12-27 05:32:44 +0000] [8] [INFO] Booting worker with pid: 8
firefox_1    | 05:32:44.721 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
chrome_1     | 05:32:44.916 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
webdriver_1  | 2019-12-27 05:32:45.240:INFO::main: Logging initialized @3364ms to org.seleniumhq.jetty9.util.log.StdErrLog
firefox_1    | 05:32:45.315 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
chrome_1     | 05:32:45.399 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 5555
chrome_1     | 2019-12-27 05:32:45.792:INFO::main: Logging initialized @1834ms to org.seleniumhq.jetty9.util.log.StdErrLog
firefox_1    | 2019-12-27 05:32:45.813:INFO::main: Logging initialized @2010ms to org.seleniumhq.jetty9.util.log.StdErrLog
webdriver_1  | 05:32:46.164 INFO [Hub.start] - Selenium Grid hub is up and running
webdriver_1  | 05:32:46.166 INFO [Hub.start] - Nodes should register to http://172.18.0.5:4444/grid/register/
webdriver_1  | 05:32:46.167 INFO [Hub.start] - Clients should connect to http://172.18.0.5:4444/wd/hub
web_1        | [2019-12-27 05:32:46 +0000] [8] [ERROR] Exception in worker process
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1        |     worker.init_process()
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
web_1        |     self.load_wsgi()
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
web_1        |     self.wsgi = self.app.wsgi()
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1        |     self.callable = self.load()
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
web_1        |     return self.load_wsgiapp()
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
web_1        |     return util.import_app(self.app_uri)
web_1        |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
web_1        |     __import__(module)
web_1        |   File "/code/eahub/config/wsgi.py", line 3, in <module>
web_1        |     application = get_wsgi_application()
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web_1        |     django.setup(set_prefix=False)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
web_1        |     apps.populate(settings.INSTALLED_APPS)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
web_1        |     app_config.ready()
web_1        |   File "/usr/local/lib/python3.7/site-packages/django_cleanup/apps.py", line 17, in ready
web_1        |     cache.prepare()
web_1        |   File "/usr/local/lib/python3.7/site-packages/django_cleanup/cache.py", line 46, in prepare
web_1        |     add_field_for_model(name, field.name, field)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django_cleanup/cache.py", line 57, in add_field_for_model
web_1        |     FIELDS_STORAGE[model_name][field_name] = get_dotted_path(field.storage)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django_cleanup/cache.py", line 112, in get_dotted_path
web_1        |     return DOTTED_PATH.format(klass=object_.__class__)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
web_1        |     self._setup()
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 363, in _setup
web_1        |     self._wrapped = get_storage_class()()
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/core/files/storage.py", line 358, in get_storage_class
web_1        |     return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
web_1        |   File "/usr/local/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
web_1        |     module = import_module(module_path)
web_1        |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1        |     return _bootstrap._gcd_import(name[level:], package, level)
web_1        |   File "/usr/local/lib/python3.7/site-packages/storages/backends/azure_storage.py", line 8, in <module>
web_1        |     from azure.common import AzureMissingResourceHttpError
web_1        | ModuleNotFoundError: No module named 'azure.common'
web_1        | [2019-12-27 05:32:46 +0000] [8] [INFO] Worker exiting (pid: 8)
web_1        | [2019-12-27 05:32:46 +0000] [1] [INFO] Shutting down: Master
web_1        | [2019-12-27 05:32:46 +0000] [1] [INFO] Reason: Worker failed to boot.
chrome_1     | 05:32:46.612 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
firefox_1    | 05:32:46.619 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
firefox_1    | 05:32:46.868 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
firefox_1    | 05:32:46.869 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1     | 05:32:46.874 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
chrome_1     | 05:32:46.876 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
chrome_1     | 05:32:47.059 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
firefox_1    | 05:32:47.067 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
eahuborg_web_1 exited with code 3
chrome_1     | 05:32:48.293 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://webdriver:4444/grid/register
firefox_1    | 05:32:48.302 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://webdriver:4444/grid/register
webdriver_1  | 05:32:48.449 INFO [DefaultGridRegistry.add] - Registered a node http://172.18.0.7:5555
firefox_1    | 05:32:48.450 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
webdriver_1  | 05:32:48.456 INFO [DefaultGridRegistry.add] - Registered a node http://172.18.0.8:5555
chrome_1     | 05:32:48.456 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
^CGracefully stopping... (press Ctrl+C again to force)
Killing eahuborg_chrome_1     ... done
Killing eahuborg_firefox_1    ... done
Killing eahuborg_webdriver_1  ... done
Killing eahuborg_cache_1      ... done
Killing eahuborg_db_1         ... done
Killing eahuborg_objstore_1   ... done
Killing eahuborg_mail_1       ... done
```

**Comment by taymonbeal** [comment]
I thought I had fixed this bug. If you update to the latest master and then run `docker-compose up --build`, does the problem go away?

**Comment by patbl** [comment]
It does! I must've run `build` on my Linux computer and not my Mac.
